# Generated by Django 4.1.7 on 2024-05-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getpid_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
